export type SeoPage = {
  slug: string;
  title: string;
  description: string;
  heading: string;
  intro: string;
  points: string[];
  cta: string;
  href: "/register?intent=invoice" | "/register?intent=quotation" | "/register?intent=receipt";
};

export const SEO_PAGES: SeoPage[] = [
  {
    slug: "invoice-generator",
    title: "Invoice Generator",
    description: "Create professional invoices in seconds. Add customers, items, tax and share a PDF or WhatsApp link.",
    heading: "Invoice generator for small businesses",
    intro: "Build a clean invoice, preview the PDF, and send it the same way your customer already messages you.",
    points: ["Automatic totals", "Payment tracking", "WhatsApp and email sharing", "Secure customer links"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "free-invoice-generator",
    title: "Free Invoice Generator",
    description: "Create up to 10 professional invoices each month for free. No expensive accounting software required.",
    heading: "Free invoice generator",
    intro: "Start on the free plan. Create invoices, keep customers, and export PDFs without a subscription.",
    points: ["10 documents each month", "Customer list", "Product catalogue", "PDF export"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "quotation-generator",
    title: "Quotation Generator",
    description: "Create professional quotations, send them for acceptance, then convert accepted quotes into invoices.",
    heading: "Quotation generator",
    intro: "Price the job once. When the customer accepts, convert the quotation into an invoice without retyping.",
    points: ["Validity dates", "Customer acceptance", "Convert to invoice", "Construction categories"],
    cta: "Create Quotation",
    href: "/register?intent=quotation",
  },
  {
    slug: "free-quotation-generator",
    title: "Free Quotation Generator",
    description: "Create quotations for free, share a view link, and let customers accept or reject the offer.",
    heading: "Free quotation generator",
    intro: "Send a priced offer that looks finished. Keep the same items when the work becomes an invoice.",
    points: ["Professional templates", "Accept or reject links", "WhatsApp sharing", "No retyping"],
    cta: "Create Quotation",
    href: "/register?intent=quotation",
  },
  {
    slug: "receipt-generator",
    title: "Receipt Generator",
    description: "Record a payment and create a receipt from the invoice so the balance and history stay accurate.",
    heading: "Receipt generator",
    intro: "Receipts should come from invoices, not from a blank form. That keeps paid, outstanding and history aligned.",
    points: ["Created from invoices", "Partial payments", "Payment method and reference", "Customer history"],
    cta: "Create Free Invoice",
    href: "/register?intent=receipt",
  },
  {
    slug: "proforma-invoice-generator",
    title: "Proforma Invoice Generator",
    description: "Create proforma invoices for deposits, imports and advance billing without mixing them up with tax invoices.",
    heading: "Proforma invoice generator",
    intro: "Use a proforma when you need a priced document before the final invoice. Convert it when the sale is confirmed.",
    points: ["Separate document type", "Same calculation engine", "Professional PDF", "Customer sharing"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "estimate-generator",
    title: "Estimate Generator",
    description: "Create estimates for jobs that are not yet firmly quoted, then refine them into quotations or invoices.",
    heading: "Estimate generator",
    intro: "Estimates help you reply quickly. Keep them numbered and dated so the conversation stays tidy.",
    points: ["Fast item entry", "Optional tax and delivery", "Convert later", "Mobile friendly"],
    cta: "Create Quotation",
    href: "/register?intent=quotation",
  },
  {
    slug: "invoice-maker",
    title: "Invoice Maker",
    description: "Make invoices on your phone or computer. Search customers, add products, review the total, then share.",
    heading: "Invoice maker",
    intro: "The path is short: customer, items, total, share. Built for shops, sites and people who invoice from a phone.",
    points: ["Under 60 seconds", "Product search", "WhatsApp share", "Payment tracking"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "online-invoice-generator",
    title: "Online Invoice Generator",
    description: "Create and store invoices online. Your customers, products and document history stay in one workspace.",
    heading: "Online invoice generator",
    intro: "Browser-based invoicing with a document history you can search later. No desktop install.",
    points: ["Cloud workspace", "Secure links", "PDF download", "Multi-currency ready"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "invoice-pdf-generator",
    title: "Invoice PDF Generator",
    description: "Generate A4 invoices as PDFs with page breaks, totals and your business details.",
    heading: "Invoice PDF generator",
    intro: "Long invoices continue onto the next page. Rows are not cut in half. Page numbers stay in the footer.",
    points: ["A4 layout", "Page breaks", "Preview before download", "Shareable link"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "quote-generator",
    title: "Quote Generator",
    description: "Create quotes with items, tax, delivery and terms. Send a link the customer can accept.",
    heading: "Quote generator",
    intro: "A quote should be easy to say yes to. Show the total clearly and keep the items ready for the invoice.",
    points: ["Line items", "Delivery and tax", "Acceptance tracking", "Convert to invoice"],
    cta: "Create Quotation",
    href: "/register?intent=quotation",
  },
  {
    slug: "business-invoice-generator",
    title: "Business Invoice Generator",
    description: "Invoicing software for small businesses that need professional documents without accounting overhead.",
    heading: "Business invoice generator",
    intro: "Keep customers, products, invoices and receipts together. Add reports when you outgrow a spreadsheet.",
    points: ["Customer history", "Outstanding balances", "Reports", "Configurable plans"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "contractor-invoice-generator",
    title: "Contractor Invoice Generator",
    description: "Invoice labour, materials and call-out fees. Convert accepted quotations into invoices in one step.",
    heading: "Contractor invoice generator",
    intro: "Contractors win work with quotations and get paid with invoices. Keep both documents connected.",
    points: ["Materials and labour", "Site-friendly mobile flow", "WhatsApp sending", "Payment balances"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "construction-quotation-generator",
    title: "Construction Quotation Generator",
    description: "Create construction quotations with materials, labour, equipment, transport and installation.",
    heading: "Construction quotation generator",
    intro: "Split the job into categories so the customer can see where the money goes. Add delivery and a validity date.",
    points: ["Construction template", "Category line items", "Validity date", "Convert to invoice"],
    cta: "Create Quotation",
    href: "/register?intent=quotation",
  },
  {
    slug: "freelance-invoice-generator",
    title: "Freelance Invoice Generator",
    description: "Simple invoicing for freelancers who send a handful of invoices each month and want them to look professional.",
    heading: "Freelance invoice generator",
    intro: "Add a client, one or two services, and send. The free plan is enough for many freelancers.",
    points: ["Fast first invoice", "Logo and branding", "Email or WhatsApp", "Low-cost paid plans"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "wholesale-invoice-generator",
    title: "Wholesale Invoice Generator",
    description: "Create wholesale invoices from a product catalogue. Duplicate repeat orders and track partial payments.",
    heading: "Wholesale invoice generator",
    intro: "Search SKUs, add quantities, and keep a running customer balance. Built for repeat trade, not one-off templates.",
    points: ["Product catalogue", "Duplicate documents", "Partial payments", "CSV import"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "small-business-invoice-generator",
    title: "Small Business Invoice Generator",
    description: "Affordable invoicing and quotation software for retailers, service businesses and online sellers.",
    heading: "Small business invoice generator",
    intro: "Professional documents without the price of full accounting software. Start free, upgrade only when volume grows.",
    points: ["Free plan", "Local payment methods on invoices", "Mobile first", "Reports"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "ghana-invoice-generator",
    title: "Ghana Invoice Generator",
    description: "Create GH₵ invoices for Ghanaian businesses. Add Mobile Money details and send the document on WhatsApp.",
    heading: "Invoice generator for Ghana",
    intro: "Price in Ghanaian cedis, show MTN MoMo or Telecel Cash only if you actually accept them, and share a WhatsApp link.",
    points: ["GH₵ formatting", "Mobile Money fields you control", "WhatsApp workflow", "Jiji and shop sellers"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "nigeria-invoice-generator",
    title: "Nigeria Invoice Generator",
    description: "Create Naira invoices for Nigerian freelancers, shops and service businesses.",
    heading: "Invoice generator for Nigeria",
    intro: "Use ₦ totals, bank transfer details, and a shareable PDF. Local billing methods appear only when a provider is configured.",
    points: ["NGN formatting", "Customer history", "PDF and WhatsApp", "Paystack-ready billing"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "kenya-invoice-generator",
    title: "Kenya Invoice Generator",
    description: "Create KSh invoices and quotations. Show M-Pesa details on documents when you accept M-Pesa.",
    heading: "Invoice generator for Kenya",
    intro: "Built for Kenyan small businesses that quote on WhatsApp and collect through M-Pesa or bank transfer.",
    points: ["KES formatting", "M-Pesa details you choose", "Quotations to invoices", "Overdue tracking"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "south-africa-invoice-generator",
    title: "South Africa Invoice Generator",
    description: "Create Rand invoices with your own tax settings. Do not copy a VAT rate — configure the rate you use.",
    heading: "Invoice generator for South Africa",
    intro: "Use ZAR, your registered tax name and rate, and professional PDFs. Tax is configurable, never hard-coded.",
    points: ["ZAR formatting", "Configurable tax", "Customer statements path", "Reports"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "india-invoice-generator",
    title: "India Invoice Generator",
    description: "Create INR invoices and quotations. Configure GST yourself. UPI appears on billing only when the provider supports it.",
    heading: "Invoice generator for India",
    intro: "Price in rupees, add GST as you are registered to charge it, and keep a clean document history for each customer.",
    points: ["INR formatting", "Configurable GST", "Product catalogue", "Secure share links"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "uk-invoice-generator",
    title: "UK Invoice Generator",
    description: "Create GBP invoices for freelancers and small UK businesses without paying for full accounting software.",
    heading: "Invoice generator for the UK",
    intro: "Use £ totals, your own VAT settings, and a professional template. Card checkout is available when Stripe is configured.",
    points: ["GBP formatting", "Configurable VAT", "Recurring invoices on paid plans", "Reports"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "usa-invoice-generator",
    title: "USA Invoice Generator",
    description: "Create USD invoices for US freelancers and small businesses. Sales tax is configurable per business.",
    heading: "Invoice generator for the United States",
    intro: "Simple invoicing with USD formatting and your own sales tax rate. No need to adopt a full accounting suite.",
    points: ["USD formatting", "Configurable sales tax", "Customer and product lists", "Card billing when configured"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
  {
    slug: "uae-invoice-generator",
    title: "UAE Invoice Generator",
    description: "Create AED invoices and quotations for UAE freelancers and small companies.",
    heading: "Invoice generator for the UAE",
    intro: "Use AED, add the tax settings that apply to your business, and send professional PDFs to clients.",
    points: ["AED formatting", "Configurable tax", "English-first interface", "Secure links"],
    cta: "Create Free Invoice",
    href: "/register?intent=invoice",
  },
];

export function getSeoPage(slug: string) {
  return SEO_PAGES.find((page) => page.slug === slug);
}
